# Generated by Django 2.0.7 on 2019-03-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=64, verbose_name='address')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('lat', models.FloatField(verbose_name='lat')),
                ('lng', models.FloatField(verbose_name='lng')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
